# Generated by Django 6.0 on 2026-09-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expense_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('expense_title', models.CharField(max_length=100)),
                ('expense_category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('paid_by', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='newbooking',
            fields=[
                ('booking_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('nic_number', models.CharField(max_length=15, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_guest', models.IntegerField()),
                ('event_hall', models.CharField(max_length=10)),
                ('special_req', models.CharField(max_length=500, null=True)),
                ('hall_price', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=40)),
                ('staff_email', models.EmailField(max_length=254, null=True)),
                ('staff_number', models.CharField(max_length=13)),
                ('staff_role', models.CharField(max_length=30)),
                ('staff_nic_num', models.CharField(max_length=16, unique=True)),
                ('staff_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=20)),
                ('inventory_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('damage_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_management.inventorycategory')),
            ],
        ),
    ]
