# Generated by Django 6.0 on 2026-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbooking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
