# Generated by Django 6.0 on 2026-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_management', '0002_newbooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbooking',
            name='event_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
